export type BookingStatus = 'Confirmed' | 'Active' | 'Completed' | 'Cancelled' | 'Pending';
export type PaymentStatus = 'Paid' | 'Pending' | 'Refunded' | 'Failed';
export type VehicleType = 'Car' | 'Bike';

export interface Booking {
  id: string;
  vehicleName: string;
  vehicleBrand: string;
  vehicleType: VehicleType;
  pickupDate: string;
  returnDate: string;
  pickupLocation: string;
  durationDays: number;
  baseAmount: number;
  insuranceFee: number;
  driverFee: number;
  gst: number;
  deposit: number;
  totalAmount: number;
  status: BookingStatus;
  paymentStatus: PaymentStatus;
  paymentMethod: string;
  kmDriven?: number;
  kmLimit: number;
  fuelType: string;
  createdAt: string;
  notes?: string;
  hasDriver: boolean;
  hasInsurance: boolean;
}

export const BOOKINGS: Booking[] = [
  {
    id: 'BK-84201',
    vehicleName: 'Nexon EV',
    vehicleBrand: 'Tata',
    vehicleType: 'Car',
    pickupDate: '22 Apr 2026',
    returnDate: '25 Apr 2026',
    pickupLocation: 'Koramangala, Bengaluru',
    durationDays: 3,
    baseAmount: 6597,
    insuranceFee: 597,
    driverFee: 0,
    gst: 1296,
    deposit: 5000,
    totalAmount: 8490,
    status: 'Active',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI — GPay',
    kmDriven: 87,
    kmLimit: 300,
    fuelType: 'Electric',
    createdAt: '21 Apr 2026',
    hasDriver: false,
    hasInsurance: true,
  },
  {
    id: 'BK-81947',
    vehicleName: 'Royal Enfield Classic 350',
    vehicleBrand: 'Royal Enfield',
    vehicleType: 'Bike',
    pickupDate: '18 Apr 2026',
    returnDate: '20 Apr 2026',
    pickupLocation: 'Indiranagar, Bengaluru',
    durationDays: 2,
    baseAmount: 1398,
    insuranceFee: 398,
    driverFee: 0,
    gst: 323,
    deposit: 2000,
    totalAmount: 2119,
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'Credit Card — HDFC',
    kmDriven: 214,
    kmLimit: 300,
    fuelType: 'Petrol',
    createdAt: '16 Apr 2026',
    hasDriver: false,
    hasInsurance: true,
  },
  {
    id: 'BK-79340',
    vehicleName: 'Innova Crysta',
    vehicleBrand: 'Toyota',
    vehicleType: 'Car',
    pickupDate: '28 Apr 2026',
    returnDate: '30 Apr 2026',
    pickupLocation: 'MG Road, Bengaluru',
    durationDays: 2,
    baseAmount: 6998,
    insuranceFee: 398,
    driverFee: 1000,
    gst: 1512,
    deposit: 7000,
    totalAmount: 9908,
    status: 'Confirmed',
    paymentStatus: 'Paid',
    paymentMethod: 'Net Banking — SBI',
    kmLimit: 300,
    fuelType: 'Diesel',
    createdAt: '20 Apr 2026',
    hasDriver: true,
    hasInsurance: true,
    notes: 'Airport pickup — Terminal 2, arrival 06:30.',
  },
  {
    id: 'BK-76812',
    vehicleName: 'KTM Duke 390',
    vehicleBrand: 'KTM',
    vehicleType: 'Bike',
    pickupDate: '10 Apr 2026',
    returnDate: '12 Apr 2026',
    pickupLocation: 'Electronic City, Bengaluru',
    durationDays: 2,
    baseAmount: 1798,
    insuranceFee: 0,
    driverFee: 0,
    gst: 324,
    deposit: 3000,
    totalAmount: 2122,
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI — PhonePe',
    kmDriven: 298,
    kmLimit: 350,
    fuelType: 'Petrol',
    createdAt: '08 Apr 2026',
    hasDriver: false,
    hasInsurance: false,
  },
  {
    id: 'BK-73501',
    vehicleName: 'Swift Dzire',
    vehicleBrand: 'Maruti Suzuki',
    vehicleType: 'Car',
    pickupDate: '05 Apr 2026',
    returnDate: '06 Apr 2026',
    pickupLocation: 'HSR Layout, Bengaluru',
    durationDays: 1,
    baseAmount: 1299,
    insuranceFee: 199,
    driverFee: 0,
    gst: 270,
    deposit: 3000,
    totalAmount: 1768,
    status: 'Completed',
    paymentStatus: 'Refunded',
    paymentMethod: 'Debit Card — Axis',
    kmDriven: 112,
    kmLimit: 250,
    fuelType: 'Petrol',
    createdAt: '04 Apr 2026',
    notes: 'Returned 2 hours early. Deposit refunded on 07 Apr.',
    hasDriver: false,
    hasInsurance: true,
  },
  {
    id: 'BK-70284',
    vehicleName: 'Himalayan 450',
    vehicleBrand: 'Royal Enfield',
    vehicleType: 'Bike',
    pickupDate: '02 May 2026',
    returnDate: '05 May 2026',
    pickupLocation: 'Yelahanka, Bengaluru',
    durationDays: 3,
    baseAmount: 3297,
    insuranceFee: 597,
    driverFee: 0,
    gst: 701,
    deposit: 4000,
    totalAmount: 4595,
    status: 'Confirmed',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI — GPay',
    kmLimit: 500,
    fuelType: 'Petrol',
    createdAt: '22 Apr 2026',
    notes: 'Coorg trip — will need full tank on pickup.',
    hasDriver: false,
    hasInsurance: true,
  },
  {
    id: 'BK-68109',
    vehicleName: 'Fortuner Legender',
    vehicleBrand: 'Toyota',
    vehicleType: 'Car',
    pickupDate: '15 Mar 2026',
    returnDate: '18 Mar 2026',
    pickupLocation: 'Sarjapur Road, Bengaluru',
    durationDays: 3,
    baseAmount: 14997,
    insuranceFee: 597,
    driverFee: 1500,
    gst: 3078,
    deposit: 10000,
    totalAmount: 20172,
    status: 'Cancelled',
    paymentStatus: 'Refunded',
    paymentMethod: 'Credit Card — ICICI',
    kmLimit: 400,
    fuelType: 'Diesel',
    createdAt: '12 Mar 2026',
    notes: 'Cancelled due to trip change. Refund processed in 3 days.',
    hasDriver: true,
    hasInsurance: true,
  },
  {
    id: 'BK-65430',
    vehicleName: 'Activa 6G',
    vehicleBrand: 'Honda',
    vehicleType: 'Bike',
    pickupDate: '20 Mar 2026',
    returnDate: '21 Mar 2026',
    pickupLocation: 'Jayanagar, Bengaluru',
    durationDays: 1,
    baseAmount: 349,
    insuranceFee: 199,
    driverFee: 0,
    gst: 98,
    deposit: 1500,
    totalAmount: 646,
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI — Paytm',
    kmDriven: 44,
    kmLimit: 200,
    fuelType: 'Petrol',
    createdAt: '19 Mar 2026',
    hasDriver: false,
    hasInsurance: true,
  },
  {
    id: 'BK-62017',
    vehicleName: 'Baleno',
    vehicleBrand: 'Maruti Suzuki',
    vehicleType: 'Car',
    pickupDate: '08 Mar 2026',
    returnDate: '09 Mar 2026',
    pickupLocation: 'JP Nagar, Bengaluru',
    durationDays: 1,
    baseAmount: 1499,
    insuranceFee: 199,
    driverFee: 500,
    gst: 396,
    deposit: 3500,
    totalAmount: 2594,
    status: 'Completed',
    paymentStatus: 'Paid',
    paymentMethod: 'Credit Card — SBI',
    kmDriven: 78,
    kmLimit: 250,
    fuelType: 'Petrol',
    createdAt: '07 Mar 2026',
    hasDriver: true,
    hasInsurance: true,
  },
  {
    id: 'BK-58843',
    vehicleName: 'Ola S1 Pro',
    vehicleBrand: 'Ola Electric',
    vehicleType: 'Bike',
    pickupDate: '01 Mar 2026',
    returnDate: '02 Mar 2026',
    pickupLocation: 'Hebbal, Bengaluru',
    durationDays: 1,
    baseAmount: 499,
    insuranceFee: 0,
    driverFee: 0,
    gst: 90,
    deposit: 2500,
    totalAmount: 589,
    status: 'Pending',
    paymentStatus: 'Pending',
    paymentMethod: '—',
    kmLimit: 150,
    fuelType: 'Electric',
    createdAt: '22 Apr 2026',
    hasDriver: false,
    hasInsurance: false,
  },
];